---
language: python
services: docker

env:
  global:
    - ROLE_NAME: rsyslog
  matrix:
    - MOLECULE_DISTRO: centos/systemd

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-$ROLE_NAME dmitrii-ageev.$ROLE_NAME
  - cd dmitrii-ageev.$ROLE_NAME

script:
  # Run tests.
  - molecule --debug test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
