---
- name: Check if we support the OS distribution
  assert:
    that:
      - ansible_distribution not in rsyslog__packages
    msg: "The {{ ansible_distribution }} operating system is not supported!"

- name: Check if we support the RedHat version
  assert:
    that:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version|int not in rsyslog__packages.RedHat
    msg: "The {{ ansible_distribution }} version {{ ansible_distribution_major_version }} is not supported!"

- name: Check if we support the CentOS version
  assert:
    that:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version|int not in rsyslog__packages.CentOS
    msg: "The {{ ansible_distribution }} version {{ ansible_distribution_major_version }} is not supported!"

- name: Check if we support the Debian version
  assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version|int not in rsyslog__packages.Debian
    msg: "The {{ ansible_distribution }} version {{ ansible_distribution_major_version }} is not supported!"

- name: Check if we support the Ubuntu version
  assert:
    that:
      - ansible_distribution == "Ubuntu"
      - ansible_distribution_major_version|int not in rsyslog__packages.Ubuntu
    msg: "The {{ ansible_distribution }} version {{ ansible_distribution_major_version }} is not supported!"
...
